###################
# Install gettext #
###################

# Detect gettexts's presence
- stat: path={{STOW_PATH}}/../bin/gettext
  register: gettext_bin
  changed_when: gettext_bin.stat.exists == False

# Upload & extract source
- { include: upload_src.yml, package: "{{src.gettext}}", pkg_check: "{{gettext_bin}}" }

- name: Install gettext
  when: gettext_bin.stat.exists == False
  shell:
    "{{src_bash}}
    cd {{SRC_PATH}}/{{src_folder.stdout}};
    ./configure --prefix={{STOW_PATH}}/{{src_folder.stdout}};
    make;
    make install prefix={{STOW_PATH}}/{{src_folder.stdout}};
    cd {{STOW_PATH}};
    stow {{src_folder.stdout}}"
  register: gettext_install
  changed_when: gettext_install.rc != 0 or gettext_bin.stat.exists == False

- stat: path={{STOW_PATH}}/../bin/gettext
  register: gettext_bin
  changed_when: gettext_bin.stat.exists == False
  failed_when: gettext_bin.stat.exists == False

- name: Display gettext symlink source
  debug: msg="{{gettext_bin.stat.lnk_source}}"
  failed_when: '"{{src.gettext.ver}}" not in gettext_bin.stat.lnk_source'
