####################
# Install GNU Stow #
####################

- name: Create expected directories | [STOW, SRC]
  file: path={{item}} state=directory
  with_items:
    - "{{STOW_PATH}}"
    - "{{SRC_PATH}}"

- name: Document STOW Vars
  lineinfile:
    dest={{HOME.stdout}}/.bash_support
    state=present
    insertafter=EOF
    create=True
    regexp='^#STOW Variables'
    line='#STOW Variables'

- name: Ensure $SRC is defined
  lineinfile:
    dest={{HOME.stdout}}/.bash_support
    regexp="^export SRC={{SRC_PATH}}$"
    line="export SRC={{SRC_PATH}}"
    state=present
    insertafter=EOF
    create=True

- name: Ensure $STOW is defined
  lineinfile:
    dest={{HOME.stdout}}/.bash_support
    regexp="^export STOW={{STOW_PATH}}$"
    line="export STOW={{STOW_PATH}}"
    state=present
    insertafter=EOF
    create=True

- name: Ensure stow's bin has precedence over $PATH
  lineinfile:
    dest={{HOME.stdout}}/.bash_support
    regexp="^export PATH=.*STOW.*:.*PATH"
    line="export PATH=${STOW}/../bin:${PATH}"
    state=present
    insertafter=EOF
    create=True

# Detect stow's presence
- stat: path={{STOW_PATH}}/../bin/stow
  register: stow_bin

# Upload & extract source
- { include: upload_src.yml, package: "{{src.stow}}", pkg_check: "{{stow_bin}}" }

- name: Install GNU Stow
  when: stow_bin.stat.exists == False
  shell:
    "{{src_bash}}
    cd {{SRC_PATH}}/{{src_folder.stdout}};
    ./configure --prefix={{STOW_PATH}}/{{src_folder.stdout}};
    make;
    make install prefix={{STOW_PATH}}/{{src_folder.stdout}};
    cd {{STOW_PATH}};
    ./{{src_folder.stdout}}/bin/stow {{src_folder.stdout}}"
  register: stow_install
  changed_when: stow_install.rc != 0 or stow_bin.stat.exists == False

- shell: "{{src_bash}} stow --version"
  register: stow_version
  changed_when: stow_version.rc != 0 or stow_bin.stat.exists == False

- name: Display stow version
  debug: msg="{{stow_version.stdout}}"
  failed_when: '"{{src.stow.ver}}" not in stow_version.stdout'
