######################
# Install PostgreSQL #
######################

# Detect postgresql
- stat: path={{STOW_PATH}}/../bin/postgres
  register: psql_bin
  changed_when: psql_bin.stat.exists == False

  # Upload & extract source
- { include: upload_src.yml, package: "{{src.postgresql}}", pkg_check: "{{psql_bin}}" }

- name: postgresql data path
  file: path={{data.postgresql.path}} state=directory mode=0600

- name: Install postgresql
  when: psql_bin.stat.exists == False
  shell:
    "{{src_bash}}
    cd {{SRC_PATH}}/{{src_folder.stdout}};
    ./configure --prefix={{STOW_PATH}}/{{src_folder.stdout}};
    gmake;
    gmake install prefix={{STOW_PATH}}/{{src_folder.stdout}};
    cd {{STOW_PATH}};
    stow {{src_folder.stdout}};
    {{src_bash}}
    initdb -D {{data.postgresql.path}};"
    #postgres -D {{data.postgresql.path}} >logfile 2>&1 &;
    #createdb test;
    #psql test;"
  register: psql_install
  changed_when: psql_install.rc != 0 or psql_bin.stat.exists == False

- shell: "{{src_bash}} postgres --version"
  register: psql_version
  changed_when: psql_version.rc != 0 or psql_bin.stat.exists == False

- name: Display postgresql version
  debug: msg="{{psql_version.stdout}}"
  failed_when: '"{{src.postgresql.ver}}" not in psql_version.stdout'
