- name: Set src file name
  shell: 'custom={{package.custom_file_name != False}};
    [[ $custom = "False" ]] && echo "{{package.prefix}}{{package.name}}-{{package.ver}}{{package.suffix}}.{{package.ext}}" || echo "{{package.custom_file_name}}"'
  register: src_file_name
  changed_when: pkg_check.stat.exists == False

- name: Set package folder
  shell: 'custom={{package.custom_folder != False}};
    [[ $custom = "False" ]] && echo "{{package.prefix}}{{package.name}}-{{package.ver}}{{package.suffix}}" || echo "{{package.custom_folder}}"'
  register: src_folder
  changed_when: pkg_check.stat.exists == False

- name: Copy {{package.name}} src file to remote node
  #unarchive: src={{LOCAL_SRC_PATH}}/{{src_file_name.stdout}} dest={{SRC_PATH}}
  copy: src={{LOCAL_SRC_PATH}}/{{src_file_name.stdout}} dest={{SRC_PATH}}
  changed_when: pkg_check.stat.exists == False

- shell: 'bz2={{"bz" in package.ext}};
  [[ $bz2 = "True" ]] && echo "-xjf" || echo "-xzf" '
  when: pkg_check.stat.exists == False
  register: tar_flags
  changed_when: pkg_check.stat.exists == False

- name: Extract src file
  when: pkg_check.stat.exists == False
  shell: "cd {{SRC_PATH}};
    tar {{tar_flags.stdout}} {{SRC_PATH}}/{{src_file_name.stdout}};
    cd {{SRC_PATH}}/{{src_folder.stdout}};
    creates={{SRC_PATH}}/{{src_folder.stdout}}"
  changed_when: pkg_check.stat.exists == False

- debug: msg="{{SRC_PATH}}/{{src_file_name.stdout}} present."
